# Generated by Django 3.1.8 on 2022-03-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('project', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('no_star', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(default='@developeruche', max_length=115)),
                ('image', models.CharField(max_length=500)),
                ('source_code', models.CharField(max_length=500)),
                ('demo_url', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=500)),
                ('main_image', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech', models.ManyToManyField(to='main_app.Technology')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
