# Generated by Django 3.1.4 on 2021-07-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(default='@developeruche', max_length=115)),
                ('demo_url', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_image', to='main_app.genericfileupload')),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_source_code', to='main_app.genericfileupload')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
