# Generated by Django 3.1.4 on 2021-07-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodal',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_image', to='main_app.genericfileupload'),
        ),
        migrations.AlterField(
            model_name='projectmodal',
            name='source_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_source_code', to='main_app.genericfileupload'),
        ),
    ]
