# Generated by Django 3.1.4 on 2021-07-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210720_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodal',
            options={'ordering': ('created_at',)},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_star', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_picture', to='main_app.genericfileupload')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
