# Generated by Django 3.1.4 on 2021-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210720_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('project', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
