# Generated by Django 3.1.8 on 2022-01-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220103_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodal',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_main_image', to='main_app.genericfileupload'),
        ),
    ]
