# Generated by Django 3.1.8 on 2022-01-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_projectmodal_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodal',
            name='github',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
